set(
        MODULES
        prefetcher_fdip_l1i
        prefetcher_no_l1d
        prefetcher_no_l2c
        prefetcher_no_llc
        replacement_lru_llc
        branch_tage-sc-l
        btb-generated_hot_warm_cold_btb_set_75_25_f
)
